#!/usr/bin/env python3
import argparse
import json
import re
import sys
import typing as T
from pathlib import Path
from subprocess import run


class ExtractionError(Exception):
    pass


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument(
        "-m", "--mode", choices=["attachments", "subs"], default="subs"
    )
    parser.add_argument("-o", "--output", type=Path)
    return parser.parse_args()


def extract_track(source_path: Path, track_id: int) -> bytes:
    result = run(
        [
            "mkvextract",
            "tracks",
            "-r",
            "/dev/null",
            source_path,
            f"{track_id}:/dev/stdout",
        ],
        capture_output=True,
        check=True,
    )
    return result.stdout


def get_info(source_path: Path) -> T.Any:
    result = run(
        ["mkvmerge", "-J", source_path],
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)


def extract_attachment(source_path: Path, attachment_id: int) -> None:
    result = run(
        [
            "mkvextract",
            "attachments",
            "-r",
            "/dev/null",
            source_path,
            f"{attachment_id}:/dev/stdout",
        ],
        capture_output=True,
        check=True,
    )
    return result.stdout


def extract_subtitles(source_path: Path, output_path: Path) -> str:
    info = get_info(source_path)
    ass_track_ids = [
        track["id"] for track in info["tracks"] if track["type"] == "subtitles"
    ]
    if not ass_track_ids:
        raise ExtractionError(f'no subtitles found in "{source_path}"')
    ass = extract_track(source_path, ass_track_ids[0]).decode()
    if str(output_path) == "-":
        print(ass, end="")
    else:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(ass)


def extract_attachments(source_path: Path, output_dir: Path) -> str:
    output_dir.mkdir(parents=True, exist_ok=True)
    info = get_info(source_path)
    if not info["attachments"]:
        raise ExtractionError(f'no attachments found in "{source_path}"')
    for i, attachment in enumerate(info["attachments"]):
        target_path = output_dir / f"{i + 1}_{attachment['file_name']}"
        target_path.write_bytes(
            extract_attachment(source_path, attachment["id"])
        )
        print(
            f'Written {target_path.stat().st_size} bytes to "{target_path}"',
            file=sys.stderr,
        )


def check_deps() -> None:
    progs = ["mkvmerge", "mkvextract"]
    for prog in progs:
        try:
            run([prog, "-h"], check=True, capture_output=True, text=True)
        except FileNotFoundError:
            raise ExtractionError(
                "please install mkvtoolnix before running this script"
            )


def main() -> None:
    check_deps()
    args = parse_args()
    if args.mode == "subs":
        extract_subtitles(args.source, args.output or Path("-"))
    else:
        if args.output is None:
            args.output = Path(".")
        if str(args.output) == "-":
            raise ExtractionError("cannot extract attachments to stdout")
        extract_attachments(args.source, args.output)


if __name__ == "__main__":
    try:
        main()
    except ExtractionError as ex:
        print(str(ex).capitalize() + ".", file=sys.stderr)
